### ISSUE TITLE
Sub-Menus

### ISSUE THREAD

**Issue by AndreAlves10** [msarsha/ng2-right-click-menu#1]
Hello @msarsha,

Is it possible to have sub-menus? Just like the following:

![submenu](https://cloud.githubusercontent.com/assets/25454839/23458658/10460ce6-fe75-11e6-820c-3e663380405c.png)

Thank you!

**Comment by msarsha** [comment]
Added to my todo list!

**Comment by AndreAlves10** [comment]
Awesome!

Thanks @msarsha

**Comment by msarsha** [comment]
@AndreAlves10 Done, still need few tweaks - they are on the way.

The `IShContextMenuItem` interface have been updated to allow you to define a sub menu:

````typescript
export interface IShContextMenuItem {
  label?: string;
  divider?: boolean;
  onClick?($event: any): void;
  visible?(context: any): boolean;
  disabled?(context: any): boolean;
  subMenu?: boolean;
  subMenuItems?: IShContextMenuItem[];
}
````

I will update the readme to include details about it.

For now I have updated the example to include sub menus.

**Comment by AndreAlves10** [comment]
Thank you @msarsha! Sub-menus are very useful!
