### ISSUE TITLE
Add "id" to IShContextMenuItem

### ISSUE THREAD

**Issue by AlexLnz** [msarsha/ng2-right-click-menu#14]
Hi,

it would be practical to have an Id field in IShContextMenuItem:
```
id: string;
```

In this way it would be easy to route all clicks to one clicked-method and the clicked method could get the id of the clicked menu item.

regards,
Alex

**Comment by msarsha** [comment]
Hey,

You can route all click handlers of your menu items to the same function, the click handler will be injected with this `$event` object:

````javascript
{
    menuItem: IShContextMenuItem,
    dataContext: any
}
````

So using the `menuItem` property you can determine which item was clicked.

**Comment by AlexLnz** [comment]
Hm, can you please give a code example on how you determine which item was clicked, without checking the label?

**Comment by msarsha** [comment]
Checking the label is the only way atm.

Can you give an example case that an id will give added value? Because I'm
failing to think on such case.

**Comment by AlexLnz** [comment]
Yes. On a multi-language UI the label changes. Therefore id's are more practical.

**Comment by msarsha** [comment]
@AlexLnz Let's give a chance for first timers to submit a PR (unless you want to)

For anyone willing to submit a PR:

Add an optional id property on the [IShContextMenuItem interface](https://github.com/msarsha/ng2-right-click-menu/blob/master/src/sh-context-item.ts)

**Comment by AlexLnz** [comment]
Hey, I'm a first timer : )
What am I supposed to do. I've already cloned and added the field.

**Comment by msarsha** [comment]
@AlexLnz 

1. fork the repo

2. clone your forked repo

3. create a new local branch and make the changes

4. commit

5. push the changes to your repo `git push -u origin {branch name}`

6. on github you will now see a "Create Pull Request" button that will create a PR for merging your new branch

**Comment by AlexLnz** [comment]
PR with new field is there.
