### ISSUE TITLE
Incorrect position when used inside a 3rd party window

### ISSUE THREAD

**Issue by AlexLnz** [msarsha/ng2-right-click-menu#15]
Hi,

I tried to use the context menu on a div which is inside a window. This is from a 3rd party UI toolkit. When right-clicking the popup opens somewhere else but not at the mouse cursor position:

![incorrect-position](https://user-images.githubusercontent.com/28703709/28156963-226717c2-67b5-11e7-8ab0-0382ae5f454b.jpg)

Also when selecting the sub menu, the sub menu is shifted further (the sub menu appears far away from the place it should).

regards,
Alex

**Comment by msarsha** [comment]
Can you reproduce this behavior in plunker ?

**Comment by AlexLnz** [comment]
Unfortunately not, the UI toolkit is not extractable and I don't know which technique they use for the windows.
But I already found a solution to fix the first part. Currently I'm trying to solve the second one (sub menu offset).

**Comment by msarsha** [comment]
Awesome.

Mind sharing your solution? Others will probably also come across this issue.

Thanks.

**Comment by AlexLnz** [comment]
Sure, as I found the second one I will push the code.

**Comment by AlexLnz** [comment]
PR with fix is there.

**Comment by AlexLnz** [comment]
I've tried it with the updates of #33 and the menu is now positioned correctly.

**Comment by msarsha** [comment]
@AlexLnz  Awesome!

Thank you for checking.
