### ISSUE TITLE
Build up/change menu before opening

### ISSUE THREAD

**Issue by AlexLnz** [msarsha/ng2-right-click-menu#19]
Hi,

it would be practical if we could build up the menu just before it's opening.
The use case for this:

Let say we have a huge DIV which contains lots of child DIVs. Each child DIV can represent a certain "type" of something, let's say a disk shape, a rectangle shape or a triangle shape.
We want to assign the context menu to our huge DIV, so that it pops up, no matter where we click inside that DIV:

a) on empty space
b) on a disk shape
c) on a rectangle shape
d) on a triangle shape

Now we would like to build up the context menu dynamically, according to what has been clicked.

**Comment by msarsha** [comment]
You can use the `hidden` event to determine if a menu item should be visible.

**Comment by AlexLnz** [comment]
That's true. However in our case we have got completely different menu structure.

**Comment by msarsha** [comment]
What about setting up a different menu for each type ?

**Comment by AlexLnz** [comment]
Yes that would be possible if we would start from scratch.

However, we're migrating a project which already has the menu items infrastructure in that way implemented. It would be a huge effort to change that, without breaking running code.

**Comment by msarsha** [comment]
How would you like the API to look like?

Something like a `(onMenuOpen)` event ?

**Comment by AlexLnz** [comment]
I thought about something like onPreOpenMenu() so that opening can be cancelled there.

**Suggestion:**

As parameter it could have the menuItems list, which it can manipulate.
As result it should return true if we want to show the menu, otherwise false to cancel it.

```javascript
onPreOpenMenu( menuItems: IShContextMenuItem[] ): boolean {
  // manipulate menuItems here
  // return true if ok
  // return false to suppress opening the menu
  return true;
};
```

We would have to wait till the event is executed.

**Comment by AlexLnz** [comment]
The ability to cancel gives us the chance to link the context menu on the "drawing surface" element, or generally the container element. It would then work for all child elements automatically. If right-clicking on the container element should display no menu at all, we can shortcut it easily by returning false.

**Comment by msarsha** [comment]
```javascript
onPreOpenMenu( event: MouseEvent, menuItems: IShContextMenuItem[] ): boolean {
  // manipulate menuItems here
  // return true if ok
  // return false to suppress opening the menu
  return true;
};
```

Maybe passing the `MouseEvent` will have more future use cases?

The target element can be extracted with `event.target`.

**Comment by AlexLnz** [comment]
agree.

**Comment by msarsha** [comment]
@AlexLnz It won't be possible using the `@Output`'s `EventEmitter` since it can not return a value (it's Asynchronous).

Will think of alternative way to achieving it.

**Comment by AlexLnz** [comment]
Maybe a old-school callback function?

**Comment by msarsha** [comment]
Yeah that it the direction I'm leaning towards, a cancellation call back.
