### ISSUE TITLE
Add "data" property to IShContextMenuItem

### ISSUE THREAD

**Issue by AlexLnz** [msarsha/ng2-right-click-menu#20]
Hi,

It would be practible to have an optional "data" field in IShContextMenuItem.
This could refer to any user specific data which belongs to the menu item.

**Comment by msarsha** [comment]
You can use the `[sh-data-context]` attribute to pass any object, this object will later will be passed down to the menu events handlers.

**Comment by AlexLnz** [comment]
[sh-data-context] is on menu level, isn't it?
We need the data on menu item level.

**Comment by msarsha** [comment]
Yes, it is on menu item level.

Mind letting @rafaelkachlon submit a PR for it ?

**Comment by AlexLnz** [comment]
it's on item level?

**Comment by msarsha** [comment]
Sorry, menu level.

**Comment by AlexLnz** [comment]
Ok  ; )
> Mind letting @rafaelkachlon submit a PR for it ?
That would be great.

**Comment by msarsha** [comment]
@rafaelkachlon Done?

I want to release it with v0.0.13.
