### ISSUE TITLE
Overlay too small

### ISSUE THREAD

**Issue by AlexLnz** [msarsha/ng2-right-click-menu#21]
Hi,

Using the menu within a 3rd party UI framework which supports movable windows.
Noticed that the overlay area does not occupy the whole browser window:

![overlay-too-small](https://user-images.githubusercontent.com/28703709/28316335-c028032a-6bc2-11e7-8e10-c7fbd617439a.png)

The resulting effect is that the context menu doesn't close when clicking outside the overlay area.

**Comment by AlexLnz** [comment]
I guess the solution would be to render the context-overlay into the <body> and have it full sized.

**Comment by AlexLnz** [comment]
I think there is a much simpler solution to this. IMHO the overlay component can be replaced by using this handy directive:
https://github.com/IamAdamJowett/angular-click-outside

What do you think?

**Comment by msarsha** [comment]
The example is for ng1.

Trying to figure out what is the correct way of getting the ViewContainerRef of the body and attach the overlay component to it.

**Comment by AlexLnz** [comment]
Yes I was also searching deeply. Finally I found something that seems to work. But this morning I saw this nice "angular-click-outside" directive. Did you have a glance over it?

**Comment by msarsha** [comment]
Yes I did, it's for angular 1 - unless I'm missing something.

**Comment by AlexLnz** [comment]
Oh now I understand what you mean  :-)
What about this:
https://github.com/arkon/ng-click-outside

**Comment by msarsha** [comment]
Will have a look.

I will prefer not to add a 3rd party dependency.

**Comment by AlexLnz** [comment]
Here's the best I've found so far regarding injecting into root:

https://github.com/AlexLnz/ng2-right-click-menu.git

Check out the InjectionService of the first answer. I made some quick tests in a demo app and it seemed to work.

Probably root injection would be also a good idea for the context menu itself. Or putting the context menu as a child of the overlay ... ? Just some thoughts.

**Comment by msarsha** [comment]
Wrong link ?

**Comment by AlexLnz** [comment]
yep, *edit*

**Comment by msarsha** [comment]
Saw it too, feels a bit hacky - but I don't think there is a more elegant way of achieving it.

**Comment by AlexLnz** [comment]
Yes, I came to the same point at the end of the day.
