### ISSUE TITLE
Version number and changelog

### ISSUE THREAD

**Issue by AlexLnz** [msarsha/ng2-right-click-menu#23]
Hi msarsha,

I think the version number should be increase to 0.13 with the last change.
What about having a changelog.md also?

regards,
Alex

**Comment by msarsha** [comment]
changelog.md is a great idea and something I do plan to add.

**Comment by AlexLnz** [comment]
Do you want to increase to 0.13 for the additional "data" field?

**Comment by msarsha** [comment]
Yeah. 

Will also publish the new version to npm.

**Comment by msarsha** [comment]
npm package updated to 0.0.13
