### ISSUE TITLE
Expose click event on click handler

### ISSUE THREAD

**Issue by leandroz** [msarsha/ng2-right-click-menu#30]
Hi!, first thanks for the library!

I just started using it inside a grid that I have, and the problem I am facing is that I can't stop the propagation of the click event over the menu items, and the event is bubling up and causing some problems. It would be great to have the click event exposed for the menu items.

Thanks!

**Comment by msarsha** [comment]
Thinking about it, it might be possible to attach the mouse event to the `(onBeforeMenuOpen)` and let you call `event.stopPropagation()`.

Or invoking it internally which is the direction I'm leaning towards.

**Comment by msarsha** [comment]
Hey @leandroz 

You can use the `(onBeforeMenuOpen)` event to call `event.stopPropagation()`.

Check the read me for more details.
