### ISSUE TITLE
Menu is clipped when used inside a 3rd party window

### ISSUE THREAD

**Issue by AlexLnz** [msarsha/ng2-right-click-menu#31]
If the menu is used within a window (which is part of a third party UI framework), the menu is clipped.
It is only visible within the window. But it should be able to overlap the window borders and occupy the whole browser window.

![menu-clipped](https://user-images.githubusercontent.com/28703709/31707466-b5817e16-b3ec-11e7-81c7-cb457249aae2.png)

**Comment by AlexLnz** [comment]
I think this issue and #15 can be solved by opening the popup on the root of the document (similarly it is done in #25). Maybe it could be opened as child of the overlay from #25 ?

**Comment by msarsha** [comment]
Will try attaching to the root.

**Comment by msarsha** [comment]
related to #15.

**Comment by msarsha** [comment]
#33 should fix it.

**Comment by AlexLnz** [comment]
I've tried it with updates of #33 and the clipping problem is solved now.

Only problem now is that the menu disappears behind the window. It seems that the z-index has to be increased.

![menu](https://user-images.githubusercontent.com/28703709/32430588-3b33bf28-c2d0-11e7-8843-013e5c324c8e.png)

**Comment by msarsha** [comment]
Yes, the default is `z-index: 100`.

You can override it in your global `styles.css` with 

```css
.sh-context--container{
   z-index: 9999;
}

.sh-context-overlay{
   z-index: 9998; // one less then .sh-context--container
}
```

you might need to add `!important`

**Comment by AlexLnz** [comment]
That works nicely. 
Yes, !important is neccessary.
Thanks.
