### ISSUE TITLE
Hide on resize window + Attach menu component to app-root

### ISSUE THREAD

**Issue by vishnutsivan** [msarsha/ng2-right-click-menu#32]
I have two suggestion for this project.

**1) Hide menu on resize window.**
    On resizing window, the position of menu gets misplaced.

**2) Attach menu component to app-root.**
    I can not select menu item as I am using relative position for parent div.
    Example for html template:
```
<div style="position: relative;z-index: 2;">
  <div (onBeforeMenuOpen)="onBefore($event)" [sh-context]="items">
    Click Me !
  </div>
</div>
```

**Comment by msarsha** [comment]
Hey @vishnutsivan  !

Thank you for your suggestions.

Regarding 1, yes it will be helpful, but I personally don't see a reason why it should be implemented because I don't think it is a common use case.

Regarding 2, it is defiantly on my to do list for the next version.

**Comment by vishnutsivan** [comment]
any target date?

**Comment by msarsha** [comment]
I hope to find some time on the weekend
