### ISSUE TITLE
increase z-index to prevent the menu from appearing under other elements

### ISSUE THREAD

**Issue by msarsha** [msarsha/ng2-right-click-menu#34]
the z-index should be changed in this files:

[context component](https://github.com/msarsha/ng2-right-click-menu/blob/master/src/sh-context-menu.component.ts#L44)

[overlay component](https://github.com/msarsha/ng2-right-click-menu/blob/master/src/sh-context-menu.component.ts#L44)

@AlexLnz Let me know if you want to submit a PR.

**Comment by AlexLnz** [comment]
For me the default value of 100 is ok. I overwrite it anyway, so we are more flexible and can adjust it to the z-index of other components.

**Comment by msarsha** [comment]
I still think the default behavior should be to appear above the element. :+1:

**Comment by AlexLnz** [comment]
Hm, I was thinking that the default behavior is ok and that it is only not working in our case because our 3rd party windows are on a higher z-index.
So you want to have 9999 as default?

**Comment by msarsha** [comment]
Yeah, 9998 \ 9999 should be fine.
