### ISSUE TITLE
context  menu should also open with left click

### ISSUE THREAD

**Issue by abparasar** [msarsha/ng2-right-click-menu#36]
Hi,

I have a hamburger menu, on which I am required to open the same right click menu that i have with a left mouse click.
Please help me on how to proceed with that.

Thanks

**Comment by msarsha** [comment]
Hey @abparasar ,

This is currently not supported but it is a good feature to have.

I will find some time to think how I can implement it.

**Comment by abparasar** [comment]
Hey @msarsha 
Thank you for taking it up. This feature will be very useful on devices with does not support a right click (like an ipad), there we can open the context menu with a click on a hamburger menu.

Also please update me when can I expect this feature?
 Thanks

**Comment by msarsha** [comment]
implemented in #55

**Comment by tgibson1** [comment]
How do you use the left click feature? I am attempting to open the context menu on a button click.
