### ISSUE TITLE
Scroll buttons when menu is too high

### ISSUE THREAD

**Issue by AlexLnz** [msarsha/ng2-right-click-menu#40]
Hi,

When a menu has too many items - so that its overall height exceeds the browser's client area - then it would be useful to have scroll buttons.

* one **arrow up** button at the top of the menu (disabled if scrolling reaches the top)
* one **arrow down** button at the end of the menu (disabled if scrolling reaches the bottom)

When **clicked**, the items in the menu are scrolled **by one line** up or down.
When **clicked and hold**, the scrolling should go on continuesly.

**Comment by msarsha** [comment]
Seems related to #4
