### ISSUE TITLE
Right click menu let disappear mouseover menu

### ISSUE THREAD

**Issue by Stizzo** [msarsha/ng2-right-click-menu#42]
Hello,
I noticed that when I use this component, the mouseover menu disappear after I click on it with the right-click. 
I admit that I am new in developing, but it seems like it changes the state of the underlying menu. This does not happen when I use the normal right-click menu. 
I attach an image for better clarification. 
I hope this might be useful for further development. In case I am missing something, could you tell me what should I do in order to maintain the menu after the right click?
![problema](https://user-images.githubusercontent.com/24460564/33318440-ec39d69c-d43a-11e7-8015-dd6814127698.png)

Thank you,
Stefano

**Comment by msarsha** [comment]
Interesting...

Are you able to provide a working fiddle ?
