### ISSUE TITLE
Not able to get the scope of parent component.

### ISSUE THREAD

**Issue by shivIndewar** [msarsha/ng2-right-click-menu#43]
Here we are attaching onClick event to each menu item but the problem is that when I get a click event in my own component not able to get the scope of component instead I am getting $event as a scope for the component.

**Comment by msarsha** [comment]
I did not understand the issue, can you provide a working fiddle with the problem ?

**Comment by indiadi** [comment]
I also have the same issue. from the handling function I want to access my component properties. but "this" refers the event

**Comment by shivIndewar** [comment]
@msarsha I mean to say that On Menu Item click application is triggering item.onClick() event and providing value as menuitem and attached dataContext. Because of that In main component's attached function I am getting whole scope as provided values.
![onclick](https://user-images.githubusercontent.com/15210636/34142140-8a7dbde8-e4ab-11e7-9081-1d58e4b5e1bc.PNG)

But now I managed some how using event emitter like in following ways:  
![emitter](https://user-images.githubusercontent.com/15210636/34142183-c54915c6-e4ab-11e7-8227-b4e8217d88e7.PNG)
![functonto call event emitter](https://user-images.githubusercontent.com/15210636/34142187-c8dda5b2-e4ab-11e7-8c9f-c1ade427991a.PNG)

**Comment by msarsha** [comment]
Hey,

Try binding your click handler to the component by .bind(this)

**Comment by msarsha** [comment]
Awesome, glad it helped.

**Comment by shivIndewar** [comment]
@indiadi In my case It wont help me... I tried that but it is quite hectic. what if I have a 1000's of line code with multiple components with different parameterized constructors injected in main component at that time before calling method of injected component I need to initialize it using datacontext.
@msarsha Thanks for the trick. But you dont think it will be hectic for huge components.

**Comment by msarsha** [comment]
implemented in #55.
