### ISSUE TITLE
Styling of menu items

### ISSUE THREAD

**Issue by AlexLnz** [msarsha/ng2-right-click-menu#44]
Hello,

Is it possible to have some influence on the styling of the menu items?
For example I would like to change the space between the items.

**Comment by AlexLnz** [comment]
I could change the space (padding) by providing a global css file and overwriting this class:

```
.sh-context--container ul li{
   padding-top: 1px !important;
   padding-bottom: 1px !important;
}
```

The issue can be closed if this is the recommended way to do it.

**Comment by msarsha** [comment]
Yes, this is how it should be done.

Might be a good idea to add it to the readme.
