### ISSUE TITLE
A way to access ctx variable in the label

### ISSUE THREAD

**Issue by Hughp135** [msarsha/ng2-right-click-menu#49]
I would like to use a ctx property inside the label, for example

```
this.items= [
      {
        label: (ctx) => ctx.someString // Passing a function to the label option
        onClick: this.clickEvent,
        disabled: () => true,
      }
    ];

```

If the label option could accept a function that returns a string (with ctx as a parameter), this would be great.

Would be willing to give this a shot and make a pull request for this feature if agreed (would allow either a string OR function to be passed).

**Comment by AlexLnz** [comment]
Not sure what ctx is in your case, but normally you would write it like this, why not?

    this.items= [
      {
        label: ctx.someString,
        onClick: this.clickEvent,
        disabled: () => true,
      }
    ];
