### ISSUE TITLE
Error in Angular 4

### ISSUE THREAD

**Issue by kamaliev** [msarsha/ng2-right-click-menu#5]
<img width="592" alt="2017-04-11 21 06 39" src="https://cloud.githubusercontent.com/assets/9512672/24923646/d85a3784-1efa-11e7-99e6-5fc26bc7dd61.png">

**Comment by msarsha** [comment]
Will look into it.

**Comment by kamaliev** [comment]
I think you must add in Module some code lines

@NgModule({
...
exports: [you directives and components]
...})

**Comment by msarsha** [comment]
@kamaliev I am. [See here](https://github.com/msarsha/ng2-right-click-menu/blob/master/src/sh-context-menu.module.ts#L20)

Will have time later today to check it out.
Meanwhile, make sure everything is good on your end - importing the `ShContextMenuModule ` in your @NgModule declaration.

**Comment by msarsha** [comment]
@kamaliev Created a new project using the cli, installed the ng2-right-click-menu package and I don't have any problems using it.

This is the markup:
<img width="845" alt="screen shot 2017-04-15 at 7 48 59" src="https://cloud.githubusercontent.com/assets/6864764/25060852/2b327a36-21b0-11e7-8c90-27f085791706.png">

Component:
<img width="627" alt="screen shot 2017-04-15 at 7 50 48" src="https://cloud.githubusercontent.com/assets/6864764/25060863/449617d0-21b0-11e7-8c74-72c55e041c63.png">

NgModule:
<img width="672" alt="screen shot 2017-04-15 at 7 51 59" src="https://cloud.githubusercontent.com/assets/6864764/25060870/6f87289e-21b0-11e7-96b0-e7d663189717.png">
