### ISSUE TITLE
my plans for the library

### ISSUE THREAD

**Issue by msarsha** [msarsha/ng2-right-click-menu#54]
Hey everyone!

Now that the development env and development experience are improved I have some ideas I would like to implement.

First, the API has to change or be extended to allow the use of `ng-template` and\or content projections

This will give consumers a more flexible API.

Then, I would like to enhance the library with some extra features like suggested at #41 by @AlexLnz

I believe an improved API will allow us implement features more easily.

**Comment by msarsha** [comment]
@Hughp135

**Comment by Hughp135** [comment]
I agree templates would be a nice addition for the library.

Personally, I think the menu reposition feature in https://github.com/msarsha/ng2-right-click-menu/pull/46 is an essential feature as I am currently making an app where there will be many context menus possible near the edges of the screen.

**Comment by msarsha** [comment]
I already have the new api ready on my local machine.

Regarding repositioning, I used @angular/cdk overlay module, so the cdk is taking care of it.

There is still work to be done, but the basics and the flexibility is there.

I was able to use a custom component as the menu, as well as custom component as a menu item.

I can push it to GitHub as a PR so you can have a look at the progress and share some ideas.
