### ISSUE TITLE
use visible attribute

### ISSUE THREAD

**Issue by Observablerxjs** [msarsha/ng2-right-click-menu#63]
I would like to use the visible attribute of the shContextMenuItem but I can't find a way to do so.
Here what I tried unsuccessfully:

```
<sh-context-menu #menu>
  <ng-template shContextMenuItem let-item [visible]="isVisibleItem()">
      <div>
        Set Item
      </div>
    </ng-template>
</sh-context-menu>
 ```
```
isVisibleItem() {
    return false;
  }
```

I just tried this and it doesn't work, the item is still visible on the menu.

Can someone please make a stackblitz or a fiddle explaining how it works. Also it would be great if we could find this kind of information on the Readme. Thanks.

**Comment by Observablerxjs** [comment]
I just checked and even in the demo, the visible attribute has any effects on the fact that the item is visible or not :confused: .

**Comment by msarsha** [comment]
Hey,

The ‘isVisibleItem’ should me passed as reference, so the () are redundant.

Let me knoe if it worked for you.

**Comment by Observablerxjs** [comment]
I tried to do so but it didn't change anything it still didn't work, I managed to get around this issue by using *ngIf

```
<ng-container *ngIf="isVisibleItem()">
  <ng-template shContextMenuItem (click)="manageItem()">
      <div>
        Set item
      </div>
    </ng-template>
</ng-container>
```
So I didn't use the [visible] attribute as I couldn't find a way to make it work.

**Comment by msarsha** [comment]
It works for me.

Can you post your code?

**Comment by msarsha** [comment]
closing because no code provided.
