### ISSUE TITLE
Module not found: Error: Can't resolve 'rxjs/observable/fromEvent'

### ISSUE THREAD

**Issue by TonyLancer** [msarsha/ng2-right-click-menu#64]
I created a simple Angular 6 project and imported the library and got this error 
`Module not found: Error: Can't resolve 'rxjs/observable/fromEvent'`.

Anyone with an idea?

**Comment by msarsha** [comment]
Hey,

The library does not yet support Angular 6 (with rxjs v6).

**Comment by msarsha** [comment]
@TonyLancer package now works with Angularv7
