### ISSUE TITLE
close sub menu on mouseleave

### ISSUE THREAD

**Issue by msarsha** [msarsha/ng2-right-click-menu#7]

**Comment by ASVS-Kartheek** [comment]
Hi I'm a first timer can I work on this issue please.

**Comment by msarsha** [comment]
Sure you can!

Let me know if you need any help.

**Comment by ASVS-Kartheek** [comment]
Can you tell me the files related to this issue so that I can deliver fast. Please

**Comment by msarsha** [comment]
This is where the sub menu is being created:
https://github.com/msarsha/ng2-right-click-menu/blob/master/src/sh-context-menu.component.ts#L25-L30

Haven't though about how I want to implement it so you are free to implement it as you see fit.

Thinking about it now, maybe listen to the `mouseenter` event of all siblings `li` tags and close the sub menu when they fire (will have to exclude the `li` tag which is the sub menu's parent [here](https://github.com/msarsha/ng2-right-click-menu/blob/master/src/sh-context-menu.component.ts#L20)) .

That's it just an idea, like I said, you are free to implement it as you wish.

I'm here to answer any question you have, we can figure it out together :)

**Comment by msarsha** [comment]
@ASVS-Kartheek 
Hey, I'm guessing you had some problems setting up a development env.

Keep an eye on #11 - will be done tomorrow.

**Comment by AlexLnz** [comment]
This would also solve the problem that when having several sub menus, they would all appear on the screen without being closed:

![sub-menu](https://user-images.githubusercontent.com/28703709/34291494-bb114166-e6fc-11e7-8f48-fcfbca9c0808.png)

**Comment by msarsha** [comment]
implemented in #55
