### ISSUE TITLE
How to use with angular 4.3 

### ISSUE THREAD

**Issue by ParasShahh** [msarsha/ng2-right-click-menu#71]
which version of this package can be use with which suitable version of angular/cdk version for angular 4 project please suggest 

Thanks

**Comment by msarsha** [comment]
Hey,
v0.0.16 should work.

**Comment by ParasShahh** [comment]
Thank you.
for ng2-right-click-menu v0.0.16 
will it work without angular/cdk ?

or which version we need to add of cdk

**Comment by msarsha** [comment]
The cdk is not needed with this version.

**Comment by ParasShahh** [comment]
Thank you
