### ISSUE TITLE
onBeforeMenuOpen not available in latest version

### ISSUE THREAD

**Issue by MarcBrad** [msarsha/ng2-right-click-menu#72]
Hi,

First thanks for this nice module.

I just downloaded the latest version and 
onBeforeMenuOpen is not present.

Comparing source code 0.0.14 with the latest version, I see that this event is no longer there.

Is there a reason for that, is it replace by something else?

I need this event to conditionally open the menu.

Thanks,

**Comment by msarsha** [comment]
Hey @MarcBrad  !

You are correct, this event was removed when the whole library API changed.

Implementing something similar shouldn't be complicated, I can probably publish it in the next few hours.

Something like an `(open)="onOpen($event)"` event on the `[shAttachMenu]` directive, and the ability to prevent it from opening:

```typescript
onOpen(event){
   if(...) event.preventOpen();
}
````

**Comment by msarsha** [comment]
@MarcBrad published v1.1.1 with the (open) event.

**Comment by MarcBrad** [comment]
Thanks for the quick response MSarcha,

This works great

**Comment by msarsha** [comment]
Glad to hear.

BTW I will appreciate if you could update the readme 😄

**Comment by MarcBrad** [comment]
Sure
I'll do that later today

**Comment by tgibson1** [comment]
How is this used?
