### ISSUE TITLE
Menu not showing when toggling mobile device mode with chrome dev tools

### ISSUE THREAD

**Issue by juanf9224** [msarsha/ng2-right-click-menu#73]
when i activate device mode on chrome with chrome dev tools, menu won't pop when right clicked.
any idea why?

**Comment by juanf9224** [comment]
angular: 6.0.0
ng2-right-click-menu: 1.1.1

**Comment by juanf9224** [comment]
you can check the demo from main page, it happens there too: https://msarsha.github.io/ng2-right-click-menu/

**Comment by msarsha** [comment]
Hey!

Can you try click and hold left click?

**Comment by juanf9224** [comment]
Thanks, that works, as it should actually.
