### ISSUE TITLE
How to use Component variable or function with contextmenu click. 

### ISSUE THREAD

**Issue by tamit0402** [msarsha/ng2-right-click-menu#8]
I'm not able to use this.ui.isLoading in createCopy function.
Can you please help me.

@Component({
    selector: 'app-dashboard',
    templateUrl: './dashboard.component.html',
    styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {
    private defList: Array<any> = [];
   public ui.isLoading=false;
    public def: any = { directory: [], blueprint: [], directoryIndex: -1, blueprintIndex: -1 };

    constructor(private defService: DefService) {    }

    ngOnInit(): void {
        localStorage.path = '';
        this.loadDef();
    }
    private loadDef(): void {      
            this.ui.isLoading = !this.ui.isLoading;
            this.defService.getDef().subscribe(response => {
                this.defList = response;             
                this.ui.isLoading = !this.ui.isLoading;
            });
    }

    /**
     * Menu Item
     */
    public menuItemsBlueprint: IShContextMenuItem[] = [
        {
            label: 'Create Copy',
            onClick: this.createCopy
        },
        {
            label: 'Remove',
            onClick: this.remove
        }
    ];

   private remove(event: any) {
        console.log('clicked ', event);
    };

    private createCopy(event: any): void {
        let array =this.defList.filter((item, index) => {
            if (item.name.indexOf(event.dataContext.name + '-Copy') == 0) return item;
        })
        this.defService.getDef(event.dataContext.name).subscribe(response => {
           
        });
   }
}

-------------------------------------------------------------------------------------------------------

ShContextMenuComponent.html:7 ERROR TypeError: Cannot read property 'isLoading' of undefined
    at Object.webpackJsonp.582.DashboardComponent.createCopy [as onClick] (dashboard.component.ts:135)
    at ShContextMenuComponent.webpackJsonp.575.ShContextMenuComponent.onClick (sh-context-menu.component.js:31)
    at Object.eval [as handleEvent] (ShContextMenuComponent.html:9)
    at handleEvent (core.es5.js:11914)
    at callWithDebugContext (core.es5.js:13206)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12794)
    at dispatchEvent (core.es5.js:8814)
    at core.es5.js:9406
    at HTMLLIElement.<anonymous> (platform-browser.es5.js:2687)
    at ZoneDelegate.invokeTask (zone.js:424)

**Comment by msarsha** [comment]
`this` inside the click event is the IShContextMenuItem.

To achieve the behavior you want you will have to bind the function to the DashboardComponent:

````typescript
/**
 * Menu Item
 */
public menuItemsBlueprint: IShContextMenuItem[] = [
    {
        label: 'Create Copy',
        onClick: this.createCopy.bind(this)
    },
    {
        label: 'Remove',
        onClick: this.remove.bind(this)
    }
];
````

**Comment by msarsha** [comment]
Another option is to use arrow function.

````typescript.
private createCopy = (event: any) => {
    let array =this.defList.filter((item, index) => {
        if (item.name.indexOf(event.dataContext.name + '-Copy') == 0) return item;
    })
    this.defService.getDef(event.dataContext.name).subscribe(response => {
       
    });

````

Haven't tested it yet so will leave issue open till I do.

**Comment by msarsha** [comment]
@tamit0402 Also works with arrow function.
