### ISSUE TITLE
Html table - when page scrolled menu opens in wrong place

### ISSUE THREAD

**Issue by a30001735** [msarsha/ng2-right-click-menu#82]
Hi, I am using this in an html table. I have about 30 rows displayed which require a page scroll, but when I scroll down a bit further and try, the menu opening higher from about 3 inches higher from where it was clicked. The event data is still correct. Any thoughts?

**Comment by msarsha** [comment]
Hey,

Thank for reporting, I will investigate it.

**Comment by martyandreas** [comment]
hi @msarsha 
I have to finish my application in the next few weeks. Therefore I wanted to ask again if there will be a fix for this problem in the near future? Otherwise I am forced to use a different context menu.

**Comment by msarsha** [comment]
Hey @martyandreas,

Hopefully I will get to it in the weekend.

**Comment by msarsha** [comment]
@martyandreas @a30001735 fixed in v 1.1.3

you can see it here:
https://msarsha.github.io/ng2-right-click-menu/
